# coding: utf-8

"""
    Knowledge Stack API

    Knowledge Stack backend API for authentication and knowledge management

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ksapi.models.folder_response_or_document_response_or_workflow_definition_response_or_workflow_run_response_or_data_source_response_or_data_source_table_response_or_api_connection_response import FolderResponseOrDocumentResponseOrWorkflowDefinitionResponseOrWorkflowRunResponseOrDataSourceResponseOrDataSourceTableResponseOrApiConnectionResponse

class TestFolderResponseOrDocumentResponseOrWorkflowDefinitionResponseOrWorkflowRunResponseOrDataSourceResponseOrDataSourceTableResponseOrApiConnectionResponse(unittest.TestCase):
    """FolderResponseOrDocumentResponseOrWorkflowDefinitionResponseOrWorkflowRunResponseOrDataSourceResponseOrDataSourceTableResponseOrApiConnectionResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FolderResponseOrDocumentResponseOrWorkflowDefinitionResponseOrWorkflowRunResponseOrDataSourceResponseOrDataSourceTableResponseOrApiConnectionResponse:
        """Test FolderResponseOrDocumentResponseOrWorkflowDefinitionResponseOrWorkflowRunResponseOrDataSourceResponseOrDataSourceTableResponseOrApiConnectionResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FolderResponseOrDocumentResponseOrWorkflowDefinitionResponseOrWorkflowRunResponseOrDataSourceResponseOrDataSourceTableResponseOrApiConnectionResponse`
        """
        model = FolderResponseOrDocumentResponseOrWorkflowDefinitionResponseOrWorkflowRunResponseOrDataSourceResponseOrDataSourceTableResponseOrApiConnectionResponse()
        if include_optional:
            return FolderResponseOrDocumentResponseOrWorkflowDefinitionResponseOrWorkflowRunResponseOrDataSourceResponseOrDataSourceTableResponseOrApiConnectionResponse(
                part_type = 'API_CONNECTION',
                id = '',
                path_part_id = '',
                name = '',
                parent_path_part_id = '',
                materialized_path = '',
                system_managed = True,
                approval_state = 'not_required',
                exclude_from_qdrant = True,
                tenant_id = '',
                owner = ksapi.models.user_info.UserInfo(
                    user_id = '', 
                    first_name = '', 
                    last_name = '', ),
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                tags = [
                    ksapi.models.tag_response.TagResponse(
                        id = '', 
                        name = '', 
                        color = '', 
                        description = '', 
                        tenant_id = '', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                permissions = ksapi.models.item_permissions.ItemPermissions(
                    can_read = True, 
                    can_write = True, 
                    can_delete = True, 
                    can_approve = True, ),
                document_type = 'PDF',
                document_origin = 'SOURCE',
                active_version_id = '',
                active_version = ksapi.models.document_version_response.DocumentVersionResponse(
                    id = '', 
                    path_part_id = '', 
                    version = 56, 
                    name = '', 
                    parent_path_id = '', 
                    materialized_path = '', 
                    system_managed = True, 
                    tenant_id = '', 
                    uploader = ksapi.models.user_info.UserInfo(
                        user_id = '', 
                        first_name = '', 
                        last_name = '', ), 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    asset_s3_url = '', 
                    fast_plaintext_url = '', 
                    page_screenshot_urls = [
                        ''
                        ], 
                    system_metadata = ksapi.models.document_version_metadata.DocumentVersionMetadata(
                        source_s3 = '', 
                        cleaned_source_s3 = '', 
                        preconversion_source_s3 = '', 
                        fast_plaintext_s3 = '', 
                        hash = '', 
                        pipeline_state = null, 
                        total_pages = 56, 
                        total_sections = 56, 
                        total_chunks = 56, 
                        total_formulas = 56, 
                        xlsx_parse_result_s3 = '', 
                        xlsx_named_ranges = [
                            { }
                            ], 
                        xlsx_kpi_catalog = [
                            { }
                            ], 
                        citation_anchors = [
                            null
                            ], 
                        information_statistics = null, 
                        quota_charged = True, 
                        quota_page_count = 56, 
                        quota_idempotency_key = 'UNSET', 
                        file_md5 = 'UNSET', ), ),
                checkout = ksapi.models.document_checkout_response.DocumentCheckoutResponse(
                    tenant_id = '', 
                    document_id = '', 
                    holder = ksapi.models.user_info.UserInfo(
                        user_id = '', 
                        first_name = '', 
                        last_name = '', ), 
                    acquired_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
                description = '',
                max_run_duration_seconds = 56,
                instruction_path_part_id = '',
                is_active = True,
                approval_required = True,
                is_template = True,
                created_from_id = '',
                copy_count = 56,
                workflow_definition_id = '',
                triggered_by = ksapi.models.user_info.UserInfo(
                    user_id = '', 
                    first_name = '', 
                    last_name = '', ),
                execution_state = 'PENDING',
                started_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                completed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                run_snapshot = ksapi.models.workflow_run_snapshot.WorkflowRunSnapshot(
                    workflow_name = '', 
                    max_run_duration_seconds = 56, 
                    instruction = ksapi.models.instruction_snapshot.InstructionSnapshot(
                        path_part_id = '', 
                        materialized_path = '', 
                        part_type = 'DOCUMENT_VERSION', 
                        source_s3_uri = '', ), 
                    inputs = [
                        ksapi.models.input_snapshot.InputSnapshot(
                            path_part_id = '', 
                            materialized_path = '', 
                            part_type = 'DOCUMENT_VERSION', )
                        ], 
                    user_message = '', ),
                error = '',
                auto_start = True,
                auto_start_user_message = '',
                inputs_path_part_id = '',
                outputs_path_part_id = '',
                discussions_path_part_id = '',
                input_path_part_ids = [
                    ''
                    ],
                outputs_path_part_ids = [
                    ''
                    ],
                run_thread_id = '',
                engine = 'MYSQL',
                data_source_id = '',
                table_name = '',
                schema_name = '',
                column_config = [
                    { }
                    ],
                base_url = '',
                network_class = 'PUBLIC',
                verify_tls = True,
                api_docs = '',
                disclaimer_accepted_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                disclaimer_accepted_by = ''
            )
        else:
            return FolderResponseOrDocumentResponseOrWorkflowDefinitionResponseOrWorkflowRunResponseOrDataSourceResponseOrDataSourceTableResponseOrApiConnectionResponse(
                part_type = 'API_CONNECTION',
                id = '',
                path_part_id = '',
                name = '',
                parent_path_part_id = '',
                materialized_path = '',
                system_managed = True,
                approval_state = 'not_required',
                exclude_from_qdrant = True,
                tenant_id = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                permissions = ksapi.models.item_permissions.ItemPermissions(
                    can_read = True, 
                    can_write = True, 
                    can_delete = True, 
                    can_approve = True, ),
                document_type = 'PDF',
                document_origin = 'SOURCE',
                active_version_id = '',
                active_version = ksapi.models.document_version_response.DocumentVersionResponse(
                    id = '', 
                    path_part_id = '', 
                    version = 56, 
                    name = '', 
                    parent_path_id = '', 
                    materialized_path = '', 
                    system_managed = True, 
                    tenant_id = '', 
                    uploader = ksapi.models.user_info.UserInfo(
                        user_id = '', 
                        first_name = '', 
                        last_name = '', ), 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    asset_s3_url = '', 
                    fast_plaintext_url = '', 
                    page_screenshot_urls = [
                        ''
                        ], 
                    system_metadata = ksapi.models.document_version_metadata.DocumentVersionMetadata(
                        source_s3 = '', 
                        cleaned_source_s3 = '', 
                        preconversion_source_s3 = '', 
                        fast_plaintext_s3 = '', 
                        hash = '', 
                        pipeline_state = null, 
                        total_pages = 56, 
                        total_sections = 56, 
                        total_chunks = 56, 
                        total_formulas = 56, 
                        xlsx_parse_result_s3 = '', 
                        xlsx_named_ranges = [
                            { }
                            ], 
                        xlsx_kpi_catalog = [
                            { }
                            ], 
                        citation_anchors = [
                            null
                            ], 
                        information_statistics = null, 
                        quota_charged = True, 
                        quota_page_count = 56, 
                        quota_idempotency_key = 'UNSET', 
                        file_md5 = 'UNSET', ), ),
                description = '',
                max_run_duration_seconds = 56,
                instruction_path_part_id = '',
                is_active = True,
                approval_required = True,
                is_template = True,
                created_from_id = '',
                workflow_definition_id = '',
                triggered_by = ksapi.models.user_info.UserInfo(
                    user_id = '', 
                    first_name = '', 
                    last_name = '', ),
                execution_state = 'PENDING',
                started_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                completed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                run_snapshot = ksapi.models.workflow_run_snapshot.WorkflowRunSnapshot(
                    workflow_name = '', 
                    max_run_duration_seconds = 56, 
                    instruction = ksapi.models.instruction_snapshot.InstructionSnapshot(
                        path_part_id = '', 
                        materialized_path = '', 
                        part_type = 'DOCUMENT_VERSION', 
                        source_s3_uri = '', ), 
                    inputs = [
                        ksapi.models.input_snapshot.InputSnapshot(
                            path_part_id = '', 
                            materialized_path = '', 
                            part_type = 'DOCUMENT_VERSION', )
                        ], 
                    user_message = '', ),
                error = '',
                auto_start = True,
                inputs_path_part_id = '',
                outputs_path_part_id = '',
                discussions_path_part_id = '',
                outputs_path_part_ids = [
                    ''
                    ],
                engine = 'MYSQL',
                data_source_id = '',
                table_name = '',
                column_config = [
                    { }
                    ],
                base_url = '',
                network_class = 'PUBLIC',
                verify_tls = True,
                api_docs = '',
                disclaimer_accepted_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                disclaimer_accepted_by = '',
        )
        """

    def testFolderResponseOrDocumentResponseOrWorkflowDefinitionResponseOrWorkflowRunResponseOrDataSourceResponseOrDataSourceTableResponseOrApiConnectionResponse(self):
        """Test FolderResponseOrDocumentResponseOrWorkflowDefinitionResponseOrWorkflowRunResponseOrDataSourceResponseOrDataSourceTableResponseOrApiConnectionResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
