# coding: utf-8

"""
    Knowledge Stack API

    Knowledge Stack backend API for authentication and knowledge management

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ksapi.models.start_workflow_run_request import StartWorkflowRunRequest

class TestStartWorkflowRunRequest(unittest.TestCase):
    """StartWorkflowRunRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StartWorkflowRunRequest:
        """Test StartWorkflowRunRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StartWorkflowRunRequest`
        """
        model = StartWorkflowRunRequest()
        if include_optional:
            return StartWorkflowRunRequest(
                user_message = ''
            )
        else:
            return StartWorkflowRunRequest(
        )
        """

    def testStartWorkflowRunRequest(self):
        """Test StartWorkflowRunRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
