# coding: utf-8

"""
    Knowledge Stack API

    Knowledge Stack backend API for authentication and knowledge management

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ksapi.models.data_source_detail_response import DataSourceDetailResponse

class TestDataSourceDetailResponse(unittest.TestCase):
    """DataSourceDetailResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DataSourceDetailResponse:
        """Test DataSourceDetailResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DataSourceDetailResponse`
        """
        model = DataSourceDetailResponse()
        if include_optional:
            return DataSourceDetailResponse(
                data_source = ksapi.models.data_source_response.DataSourceResponse(
                    part_type = 'DATA_SOURCE', 
                    id = '', 
                    path_part_id = '', 
                    parent_path_part_id = '', 
                    materialized_path = '', 
                    tenant_id = '', 
                    name = '', 
                    engine = 'MYSQL', 
                    approval_state = 'not_required', 
                    owner = null, 
                    permissions = ksapi.models.item_permissions.ItemPermissions(
                        can_read = True, 
                        can_write = True, 
                        can_delete = True, 
                        can_approve = True, ), 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
                schemas = [
                    ksapi.models.data_source_schema_response.DataSourceSchemaResponse(
                        part_type = 'DATA_SOURCE_SCHEMA', 
                        id = '', 
                        path_part_id = '', 
                        parent_path_part_id = '', 
                        materialized_path = '', 
                        tenant_id = '', 
                        name = '', 
                        data_source_id = '', 
                        schema_name = '', 
                        is_default = True, 
                        description = '', 
                        approval_state = 'not_required', 
                        permissions = ksapi.models.item_permissions.ItemPermissions(
                            can_read = True, 
                            can_write = True, 
                            can_delete = True, 
                            can_approve = True, ), 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        tables = [
                            ksapi.models.data_source_table_response.DataSourceTableResponse(
                                part_type = 'DATA_SOURCE_TABLE', 
                                id = '', 
                                path_part_id = '', 
                                parent_path_part_id = '', 
                                materialized_path = '', 
                                tenant_id = '', 
                                name = '', 
                                data_source_id = '', 
                                data_source_schema_id = '', 
                                table_name = '', 
                                description = '', 
                                column_config = [
                                    { }
                                    ], 
                                approval_state = 'not_required', 
                                permissions = ksapi.models.item_permissions.ItemPermissions(
                                    can_read = True, 
                                    can_write = True, 
                                    can_delete = True, 
                                    can_approve = True, ), 
                                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                            ], )
                    ],
                description_document_id = ''
            )
        else:
            return DataSourceDetailResponse(
                data_source = ksapi.models.data_source_response.DataSourceResponse(
                    part_type = 'DATA_SOURCE', 
                    id = '', 
                    path_part_id = '', 
                    parent_path_part_id = '', 
                    materialized_path = '', 
                    tenant_id = '', 
                    name = '', 
                    engine = 'MYSQL', 
                    approval_state = 'not_required', 
                    owner = null, 
                    permissions = ksapi.models.item_permissions.ItemPermissions(
                        can_read = True, 
                        can_write = True, 
                        can_delete = True, 
                        can_approve = True, ), 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
                schemas = [
                    ksapi.models.data_source_schema_response.DataSourceSchemaResponse(
                        part_type = 'DATA_SOURCE_SCHEMA', 
                        id = '', 
                        path_part_id = '', 
                        parent_path_part_id = '', 
                        materialized_path = '', 
                        tenant_id = '', 
                        name = '', 
                        data_source_id = '', 
                        schema_name = '', 
                        is_default = True, 
                        description = '', 
                        approval_state = 'not_required', 
                        permissions = ksapi.models.item_permissions.ItemPermissions(
                            can_read = True, 
                            can_write = True, 
                            can_delete = True, 
                            can_approve = True, ), 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        tables = [
                            ksapi.models.data_source_table_response.DataSourceTableResponse(
                                part_type = 'DATA_SOURCE_TABLE', 
                                id = '', 
                                path_part_id = '', 
                                parent_path_part_id = '', 
                                materialized_path = '', 
                                tenant_id = '', 
                                name = '', 
                                data_source_id = '', 
                                data_source_schema_id = '', 
                                table_name = '', 
                                description = '', 
                                column_config = [
                                    { }
                                    ], 
                                approval_state = 'not_required', 
                                permissions = ksapi.models.item_permissions.ItemPermissions(
                                    can_read = True, 
                                    can_write = True, 
                                    can_delete = True, 
                                    can_approve = True, ), 
                                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                            ], )
                    ],
        )
        """

    def testDataSourceDetailResponse(self):
        """Test DataSourceDetailResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
