# coding: utf-8

"""
    Knowledge Stack API

    Knowledge Stack backend API for authentication and knowledge management

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ksapi.api.bulk_download_api import BulkDownloadApi


class TestBulkDownloadApi(unittest.TestCase):
    """BulkDownloadApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BulkDownloadApi()

    def tearDown(self) -> None:
        pass

    def test_start_bulk_download(self) -> None:
        """Test case for start_bulk_download

        Start Bulk Download Handler
        """
        pass


if __name__ == '__main__':
    unittest.main()
