# coding: utf-8

"""
    Knowledge Stack API

    Knowledge Stack backend API for authentication and knowledge management

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ksapi.api.workflows_api import WorkflowsApi


class TestWorkflowsApi(unittest.TestCase):
    """WorkflowsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WorkflowsApi()

    def tearDown(self) -> None:
        pass

    def test_cancel_temporal_workflow(self) -> None:
        """Test case for cancel_temporal_workflow

        Cancel Temporal Workflow Handler
        """
        pass

    def test_dv_workflow_rerun(self) -> None:
        """Test case for dv_workflow_rerun

        Dv Workflow Rerun Handler
        """
        pass

    def test_get_dv_workflow(self) -> None:
        """Test case for get_dv_workflow

        Get Dv Workflow Handler
        """
        pass

    def test_get_temporal_workflow_status(self) -> None:
        """Test case for get_temporal_workflow_status

        Get Temporal Workflow Status Handler
        """
        pass

    def test_list_dv_workflows(self) -> None:
        """Test case for list_dv_workflows

        List Dv Workflows Handler
        """
        pass


if __name__ == '__main__':
    unittest.main()
