# coding: utf-8

"""
    Knowledge Stack API

    Knowledge Stack backend API for authentication and knowledge management

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ksapi.models.update_thread_request import UpdateThreadRequest

class TestUpdateThreadRequest(unittest.TestCase):
    """UpdateThreadRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateThreadRequest:
        """Test UpdateThreadRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateThreadRequest`
        """
        model = UpdateThreadRequest()
        if include_optional:
            return UpdateThreadRequest(
                title = '0',
                parent_thread_id = ''
            )
        else:
            return UpdateThreadRequest(
        )
        """

    def testUpdateThreadRequest(self):
        """Test UpdateThreadRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
