# coding: utf-8

"""
    Knowledge Stack API

    Knowledge Stack backend API for authentication and knowledge management

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ksapi.models.cell_change import CellChange

class TestCellChange(unittest.TestCase):
    """CellChange unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CellChange:
        """Test CellChange
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CellChange`
        """
        model = CellChange()
        if include_optional:
            return CellChange(
                sheet = '',
                address = '',
                old = '',
                new = '',
                type = 'added'
            )
        else:
            return CellChange(
                sheet = '',
                address = '',
                old = '',
                new = '',
                type = 'added',
        )
        """

    def testCellChange(self):
        """Test CellChange"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
