# coding: utf-8

"""
    Knowledge Stack API

    Knowledge Stack backend API for authentication and knowledge management

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ksapi.models.paginated_response_memory_chunk_response import PaginatedResponseMemoryChunkResponse

class TestPaginatedResponseMemoryChunkResponse(unittest.TestCase):
    """PaginatedResponseMemoryChunkResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaginatedResponseMemoryChunkResponse:
        """Test PaginatedResponseMemoryChunkResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaginatedResponseMemoryChunkResponse`
        """
        model = PaginatedResponseMemoryChunkResponse()
        if include_optional:
            return PaginatedResponseMemoryChunkResponse(
                items = [
                    ksapi.models.memory_chunk_response.MemoryChunkResponse(
                        chunk_id = '', 
                        kind = 'CORRECTION', 
                        body = '', )
                    ],
                total = 0.0,
                limit = 1.0,
                offset = 0.0
            )
        else:
            return PaginatedResponseMemoryChunkResponse(
                items = [
                    ksapi.models.memory_chunk_response.MemoryChunkResponse(
                        chunk_id = '', 
                        kind = 'CORRECTION', 
                        body = '', )
                    ],
                total = 0.0,
                limit = 1.0,
                offset = 0.0,
        )
        """

    def testPaginatedResponseMemoryChunkResponse(self):
        """Test PaginatedResponseMemoryChunkResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
