# coding: utf-8

"""
    Knowledge Stack API

    Knowledge Stack backend API for authentication and knowledge management

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ksapi.models.docx_paragraph_anchor_output import DocxParagraphAnchorOutput

class TestDocxParagraphAnchorOutput(unittest.TestCase):
    """DocxParagraphAnchorOutput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DocxParagraphAnchorOutput:
        """Test DocxParagraphAnchorOutput
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DocxParagraphAnchorOutput`
        """
        model = DocxParagraphAnchorOutput()
        if include_optional:
            return DocxParagraphAnchorOutput(
                type = 'docx_paragraph',
                paragraph_index = 0.0,
                comment_id = 56,
                citations = [
                    ksapi.models.cited_chunk.CitedChunk(
                        chunk_id = '', 
                        document_id = '', 
                        document_name = '', 
                        document_type = 'PDF', 
                        document_version_id = '', 
                        version_number = 56, )
                    ],
                anchor_text = '',
                chunk_ids = [
                    ''
                    ]
            )
        else:
            return DocxParagraphAnchorOutput(
                paragraph_index = 0.0,
                comment_id = 56,
                citations = [
                    ksapi.models.cited_chunk.CitedChunk(
                        chunk_id = '', 
                        document_id = '', 
                        document_name = '', 
                        document_type = 'PDF', 
                        document_version_id = '', 
                        version_number = 56, )
                    ],
                chunk_ids = [
                    ''
                    ],
        )
        """

    def testDocxParagraphAnchorOutput(self):
        """Test DocxParagraphAnchorOutput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
