# coding: utf-8

"""
    Knowledge Stack API

    Knowledge Stack backend API for authentication and knowledge management

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ksapi.models.invite_user_request import InviteUserRequest

class TestInviteUserRequest(unittest.TestCase):
    """InviteUserRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InviteUserRequest:
        """Test InviteUserRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InviteUserRequest`
        """
        model = InviteUserRequest()
        if include_optional:
            return InviteUserRequest(
                tenant_id = '',
                email = '',
                role = 'USER'
            )
        else:
            return InviteUserRequest(
                tenant_id = '',
                email = '',
        )
        """

    def testInviteUserRequest(self):
        """Test InviteUserRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
