# coding: utf-8

"""
    Knowledge Stack API

    Knowledge Stack backend API for authentication and knowledge management

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ksapi.models.cell_change_type import CellChangeType

class TestCellChangeType(unittest.TestCase):
    """CellChangeType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCellChangeType(self):
        """Test CellChangeType"""
        # inst = CellChangeType()

if __name__ == '__main__':
    unittest.main()
