# coding: utf-8

"""
    Knowledge Stack API

    Knowledge Stack backend API for authentication and knowledge management

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ksapi.api.tenants_api import TenantsApi


class TestTenantsApi(unittest.TestCase):
    """TenantsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TenantsApi()

    def tearDown(self) -> None:
        pass

    def test_activate_tenant_user(self) -> None:
        """Test case for activate_tenant_user

        Activate Tenant User Handler
        """
        pass

    def test_deactivate_tenant_user(self) -> None:
        """Test case for deactivate_tenant_user

        Deactivate Tenant User Handler
        """
        pass

    def test_delete_tenant(self) -> None:
        """Test case for delete_tenant

        Delete Tenant
        """
        pass

    def test_delete_tenant_logo(self) -> None:
        """Test case for delete_tenant_logo

        Delete Tenant Logo
        """
        pass

    def test_delete_tenant_user(self) -> None:
        """Test case for delete_tenant_user

        Delete Tenant User Handler
        """
        pass

    def test_get_tenant(self) -> None:
        """Test case for get_tenant

        Get Tenant
        """
        pass

    def test_list_tenant_users(self) -> None:
        """Test case for list_tenant_users

        List Tenant Users
        """
        pass

    def test_list_tenants(self) -> None:
        """Test case for list_tenants

        List Tenants
        """
        pass

    def test_update_tenant(self) -> None:
        """Test case for update_tenant

        Update Tenant
        """
        pass

    def test_update_tenant_user(self) -> None:
        """Test case for update_tenant_user

        Update Tenant User
        """
        pass

    def test_upload_tenant_logo(self) -> None:
        """Test case for upload_tenant_logo

        Upload Tenant Logo
        """
        pass


if __name__ == '__main__':
    unittest.main()
