# coding: utf-8

"""
    Knowledge Stack API

    Knowledge Stack backend API for authentication and knowledge management

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ksapi.models.update_tenant_request import UpdateTenantRequest

class TestUpdateTenantRequest(unittest.TestCase):
    """UpdateTenantRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateTenantRequest:
        """Test UpdateTenantRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateTenantRequest`
        """
        model = UpdateTenantRequest()
        if include_optional:
            return UpdateTenantRequest(
                name = '',
                idp_config = ksapi.models.idp_config.IdpConfig(
                    provider = 'OAUTH2', 
                    configuration = { }, ),
                settings = ksapi.models.tenant_settings_update.TenantSettingsUpdate(
                    language = 'en', 
                    description = '', 
                    timezone = '', 
                    brand_name = '', 
                    brand_color = '', 
                    theme_overrides = {
                        'key' : ''
                        }, )
            )
        else:
            return UpdateTenantRequest(
        )
        """

    def testUpdateTenantRequest(self):
        """Test UpdateTenantRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
