# coding: utf-8

"""
    Knowledge Stack API

    Knowledge Stack backend API for authentication and knowledge management

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ksapi.models.api_connection_request_request import ApiConnectionRequestRequest

class TestApiConnectionRequestRequest(unittest.TestCase):
    """ApiConnectionRequestRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiConnectionRequestRequest:
        """Test ApiConnectionRequestRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiConnectionRequestRequest`
        """
        model = ApiConnectionRequestRequest()
        if include_optional:
            return ApiConnectionRequestRequest(
                method = '',
                path = '/',
                query = {
                    'key' : ''
                    },
                headers = {
                    'key' : ''
                    },
                body = None
            )
        else:
            return ApiConnectionRequestRequest(
                method = '',
        )
        """

    def testApiConnectionRequestRequest(self):
        """Test ApiConnectionRequestRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
