# coding: utf-8

"""
    Knowledge Stack API

    Knowledge Stack backend API for authentication and knowledge management

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ksapi.models.paginated_response_tag_response import PaginatedResponseTagResponse

class TestPaginatedResponseTagResponse(unittest.TestCase):
    """PaginatedResponseTagResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaginatedResponseTagResponse:
        """Test PaginatedResponseTagResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaginatedResponseTagResponse`
        """
        model = PaginatedResponseTagResponse()
        if include_optional:
            return PaginatedResponseTagResponse(
                items = [
                    ksapi.models.tag_response.TagResponse(
                        id = '', 
                        name = '', 
                        color = '', 
                        description = '', 
                        tenant_id = '', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                total = 0.0,
                limit = 1.0,
                offset = 0.0
            )
        else:
            return PaginatedResponseTagResponse(
                items = [
                    ksapi.models.tag_response.TagResponse(
                        id = '', 
                        name = '', 
                        color = '', 
                        description = '', 
                        tenant_id = '', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                total = 0.0,
                limit = 1.0,
                offset = 0.0,
        )
        """

    def testPaginatedResponseTagResponse(self):
        """Test PaginatedResponseTagResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
