# coding: utf-8

"""
    Knowledge Stack API

    Knowledge Stack backend API for authentication and knowledge management

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ksapi.api.document_versions_api import DocumentVersionsApi


class TestDocumentVersionsApi(unittest.TestCase):
    """DocumentVersionsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DocumentVersionsApi()

    def tearDown(self) -> None:
        pass

    def test_clear_document_version_contents(self) -> None:
        """Test case for clear_document_version_contents

        Clear Document Version Contents Handler
        """
        pass

    def test_create_document_version(self) -> None:
        """Test case for create_document_version

        Create Document Version Handler
        """
        pass

    def test_delete_document_version(self) -> None:
        """Test case for delete_document_version

        Delete Document Version Handler
        """
        pass

    def test_document_version_action(self) -> None:
        """Test case for document_version_action

        Document Version Action Handler
        """
        pass

    def test_get_document_version(self) -> None:
        """Test case for get_document_version

        Get Document Version Handler
        """
        pass

    def test_get_document_version_contents(self) -> None:
        """Test case for get_document_version_contents

        Get Document Version Contents Handler
        """
        pass

    def test_list_document_versions(self) -> None:
        """Test case for list_document_versions

        List Document Versions Handler
        """
        pass

    def test_update_document_version_metadata(self) -> None:
        """Test case for update_document_version_metadata

        Update Document Version Metadata Handler
        """
        pass


if __name__ == '__main__':
    unittest.main()
