# coding: utf-8

"""
    Knowledge Stack API

    Knowledge Stack backend API for authentication and knowledge management

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ksapi.models.billing_plan_tier import BillingPlanTier

class TestBillingPlanTier(unittest.TestCase):
    """BillingPlanTier unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBillingPlanTier(self):
        """Test BillingPlanTier"""
        # inst = BillingPlanTier()

if __name__ == '__main__':
    unittest.main()
