# coding: utf-8

"""
    Knowledge Stack API

    Knowledge Stack backend API for authentication and knowledge management

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ksapi.models.diff_row import DiffRow

class TestDiffRow(unittest.TestCase):
    """DiffRow unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DiffRow:
        """Test DiffRow
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DiffRow`
        """
        model = DiffRow()
        if include_optional:
            return DiffRow(
                type = 'equal',
                left_no = 56,
                left = '',
                right_no = 56,
                right = '',
                left_spans = [
                    ksapi.models.diff_span.DiffSpan(
                        start = 56, 
                        end = 56, )
                    ],
                right_spans = [
                    ksapi.models.diff_span.DiffSpan(
                        start = 56, 
                        end = 56, )
                    ]
            )
        else:
            return DiffRow(
                type = 'equal',
        )
        """

    def testDiffRow(self):
        """Test DiffRow"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
