# coding: utf-8

"""
    Knowledge Stack API

    Knowledge Stack backend API for authentication and knowledge management

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ksapi.models.set_enterprise_override_request import SetEnterpriseOverrideRequest

class TestSetEnterpriseOverrideRequest(unittest.TestCase):
    """SetEnterpriseOverrideRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SetEnterpriseOverrideRequest:
        """Test SetEnterpriseOverrideRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SetEnterpriseOverrideRequest`
        """
        model = SetEnterpriseOverrideRequest()
        if include_optional:
            return SetEnterpriseOverrideRequest(
                override_price_per_seat_cents = 0.0,
                override_monthly_token_limit = 0.0,
                override_monthly_document_limit = 0.0,
                override_max_seats = 1.0,
                override_litellm_budget_cents_per_user = 0.0,
                override_notes = ''
            )
        else:
            return SetEnterpriseOverrideRequest(
        )
        """

    def testSetEnterpriseOverrideRequest(self):
        """Test SetEnterpriseOverrideRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
