# coding: utf-8

"""
    Knowledge Stack API

    Knowledge Stack backend API for authentication and knowledge management

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ksapi.models.billing_plan_response import BillingPlanResponse

class TestBillingPlanResponse(unittest.TestCase):
    """BillingPlanResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BillingPlanResponse:
        """Test BillingPlanResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BillingPlanResponse`
        """
        model = BillingPlanResponse()
        if include_optional:
            return BillingPlanResponse(
                id = '',
                tier = 'FREE',
                display_name = '',
                description = '',
                monthly_price_per_seat_cents = 56,
                annual_price_per_seat_cents = 56,
                annual_discount_percent = 56,
                max_seats = 56,
                monthly_token_limit = 56,
                monthly_document_limit = 56,
                litellm_budget_cents_per_user = 56,
                sort_order = 56
            )
        else:
            return BillingPlanResponse(
                id = '',
                tier = 'FREE',
                display_name = '',
                description = '',
                monthly_price_per_seat_cents = 56,
                annual_price_per_seat_cents = 56,
                annual_discount_percent = 56,
                max_seats = 56,
                monthly_token_limit = 56,
                monthly_document_limit = 56,
                litellm_budget_cents_per_user = 56,
                sort_order = 56,
        )
        """

    def testBillingPlanResponse(self):
        """Test BillingPlanResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
