# coding: utf-8

"""
    Knowledge Stack API

    Knowledge Stack backend API for authentication and knowledge management

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ksapi.api.subscriptions_api import SubscriptionsApi


class TestSubscriptionsApi(unittest.TestCase):
    """SubscriptionsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SubscriptionsApi()

    def tearDown(self) -> None:
        pass

    def test_change_tenant_subscription(self) -> None:
        """Test case for change_tenant_subscription

        Change Tenant Subscription Handler
        """
        pass

    def test_get_tenant_subscription(self) -> None:
        """Test case for get_tenant_subscription

        Get Tenant Subscription Handler
        """
        pass


if __name__ == '__main__':
    unittest.main()
