# coding: utf-8

"""
    Knowledge Stack API

    Knowledge Stack backend API for authentication and knowledge management

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ksapi.models.chunk_search_request import ChunkSearchRequest

class TestChunkSearchRequest(unittest.TestCase):
    """ChunkSearchRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ChunkSearchRequest:
        """Test ChunkSearchRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ChunkSearchRequest`
        """
        model = ChunkSearchRequest()
        if include_optional:
            return ChunkSearchRequest(
                query = '0',
                search_type = 'dense_only',
                parent_path_ids = [
                    ''
                    ],
                tag_ids = [
                    ''
                    ],
                chunk_types = [
                    'TEXT'
                    ],
                ingestion_time_after = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                active_version_only = True,
                top_k = 1.0,
                score_threshold = 1.337,
                with_document = True
            )
        else:
            return ChunkSearchRequest(
                query = '0',
        )
        """

    def testChunkSearchRequest(self):
        """Test ChunkSearchRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
