# coding: utf-8

"""
    Knowledge Stack API

    Knowledge Stack backend API for authentication and knowledge management

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ksapi.models.pipeline_state import PipelineState

class TestPipelineState(unittest.TestCase):
    """PipelineState unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PipelineState:
        """Test PipelineState
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PipelineState`
        """
        model = PipelineState()
        if include_optional:
            return PipelineState(
                status = 'pending',
                last_run_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                last_state_update_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                last_activity = '',
                error = '',
                temporal_workflow_id = '',
                chunks_processed = 56,
                page_dpi = 56,
                ingestion_mode = 'high_accuracy',
                chunk_type = 'TEXT'
            )
        else:
            return PipelineState(
                status = 'pending',
        )
        """

    def testPipelineState(self):
        """Test PipelineState"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
