# coding: utf-8

"""
    Knowledge Stack API

    Knowledge Stack backend API for authentication and knowledge management

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ksapi.models.bulk_model_tables_request import BulkModelTablesRequest

class TestBulkModelTablesRequest(unittest.TestCase):
    """BulkModelTablesRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BulkModelTablesRequest:
        """Test BulkModelTablesRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BulkModelTablesRequest`
        """
        model = BulkModelTablesRequest()
        if include_optional:
            return BulkModelTablesRequest(
                tables = [
                    ksapi.models.model_table_request.ModelTableRequest(
                        table_name = '', 
                        schema_name = '', 
                        name = '', 
                        description = '', 
                        column_config = [
                            ksapi.models.column_config.ColumnConfig(
                                name = '', 
                                data_type = '', 
                                comment = '', 
                                is_pk = True, 
                                exposed = True, 
                                references = null, )
                            ], )
                    ]
            )
        else:
            return BulkModelTablesRequest(
                tables = [
                    ksapi.models.model_table_request.ModelTableRequest(
                        table_name = '', 
                        schema_name = '', 
                        name = '', 
                        description = '', 
                        column_config = [
                            ksapi.models.column_config.ColumnConfig(
                                name = '', 
                                data_type = '', 
                                comment = '', 
                                is_pk = True, 
                                exposed = True, 
                                references = null, )
                            ], )
                    ],
        )
        """

    def testBulkModelTablesRequest(self):
        """Test BulkModelTablesRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
