# coding: utf-8

"""
    Knowledge Stack API

    Knowledge Stack backend API for authentication and knowledge management

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ksapi.models.paginated_response_document_version_response import PaginatedResponseDocumentVersionResponse

class TestPaginatedResponseDocumentVersionResponse(unittest.TestCase):
    """PaginatedResponseDocumentVersionResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaginatedResponseDocumentVersionResponse:
        """Test PaginatedResponseDocumentVersionResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaginatedResponseDocumentVersionResponse`
        """
        model = PaginatedResponseDocumentVersionResponse()
        if include_optional:
            return PaginatedResponseDocumentVersionResponse(
                items = [
                    ksapi.models.document_version_response.DocumentVersionResponse(
                        id = '', 
                        path_part_id = '', 
                        version = 56, 
                        name = '', 
                        parent_path_id = '', 
                        materialized_path = '', 
                        system_managed = True, 
                        tenant_id = '', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        asset_s3_url = '', 
                        fast_plaintext_url = '', 
                        system_metadata = ksapi.models.document_version_metadata.DocumentVersionMetadata(
                            source_s3 = '', 
                            cleaned_source_s3 = '', 
                            fast_plaintext_s3 = '', 
                            hash = '', 
                            pipeline_state = ksapi.models.pipeline_state.PipelineState(
                                status = 'pending', 
                                last_run_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                last_state_update_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                last_activity = '', 
                                error = '', 
                                temporal_workflow_id = '', 
                                chunks_processed = 56, 
                                page_dpi = 56, 
                                ingestion_mode = 'high_accuracy', 
                                chunk_type = 'TEXT', ), 
                            total_pages = 56, 
                            total_sections = 56, 
                            total_chunks = 56, 
                            total_formulas = 56, 
                            xlsx_parse_result_s3 = '', 
                            xlsx_named_ranges = [
                                { }
                                ], 
                            xlsx_kpi_catalog = [
                                { }
                                ], 
                            information_statistics = ksapi.models.information_statistics.InformationStatistics(
                                num_chunks_by_type = {
                                    'key' : 56
                                    }, 
                                total_tokens = 56, 
                                num_direct_children = 56, 
                                children_depth = 56, ), ), )
                    ],
                total = 0.0,
                limit = 1.0,
                offset = 0.0
            )
        else:
            return PaginatedResponseDocumentVersionResponse(
                items = [
                    ksapi.models.document_version_response.DocumentVersionResponse(
                        id = '', 
                        path_part_id = '', 
                        version = 56, 
                        name = '', 
                        parent_path_id = '', 
                        materialized_path = '', 
                        system_managed = True, 
                        tenant_id = '', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        asset_s3_url = '', 
                        fast_plaintext_url = '', 
                        system_metadata = ksapi.models.document_version_metadata.DocumentVersionMetadata(
                            source_s3 = '', 
                            cleaned_source_s3 = '', 
                            fast_plaintext_s3 = '', 
                            hash = '', 
                            pipeline_state = ksapi.models.pipeline_state.PipelineState(
                                status = 'pending', 
                                last_run_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                last_state_update_timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                last_activity = '', 
                                error = '', 
                                temporal_workflow_id = '', 
                                chunks_processed = 56, 
                                page_dpi = 56, 
                                ingestion_mode = 'high_accuracy', 
                                chunk_type = 'TEXT', ), 
                            total_pages = 56, 
                            total_sections = 56, 
                            total_chunks = 56, 
                            total_formulas = 56, 
                            xlsx_parse_result_s3 = '', 
                            xlsx_named_ranges = [
                                { }
                                ], 
                            xlsx_kpi_catalog = [
                                { }
                                ], 
                            information_statistics = ksapi.models.information_statistics.InformationStatistics(
                                num_chunks_by_type = {
                                    'key' : 56
                                    }, 
                                total_tokens = 56, 
                                num_direct_children = 56, 
                                children_depth = 56, ), ), )
                    ],
                total = 0.0,
                limit = 1.0,
                offset = 0.0,
        )
        """

    def testPaginatedResponseDocumentVersionResponse(self):
        """Test PaginatedResponseDocumentVersionResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
