# coding: utf-8

"""
    Knowledge Stack API

    Knowledge Stack backend API for authentication and knowledge management

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ksapi.models.seat_quota_status import SeatQuotaStatus

class TestSeatQuotaStatus(unittest.TestCase):
    """SeatQuotaStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SeatQuotaStatus:
        """Test SeatQuotaStatus
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SeatQuotaStatus`
        """
        model = SeatQuotaStatus()
        if include_optional:
            return SeatQuotaStatus(
                used = 56,
                limit = 56
            )
        else:
            return SeatQuotaStatus(
                used = 56,
                limit = 56,
        )
        """

    def testSeatQuotaStatus(self):
        """Test SeatQuotaStatus"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
