# coding: utf-8

"""
    Knowledge Stack API

    Knowledge Stack backend API for authentication and knowledge management

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ksapi.models.effective_limits_response import EffectiveLimitsResponse

class TestEffectiveLimitsResponse(unittest.TestCase):
    """EffectiveLimitsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EffectiveLimitsResponse:
        """Test EffectiveLimitsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EffectiveLimitsResponse`
        """
        model = EffectiveLimitsResponse()
        if include_optional:
            return EffectiveLimitsResponse(
                price_per_seat_cents_monthly = 56,
                price_per_seat_cents_billed = 56,
                monthly_token_limit = 56,
                monthly_document_limit = 56,
                max_seats = 56,
                litellm_budget_cents_per_user = 56,
                has_custom_overrides = True
            )
        else:
            return EffectiveLimitsResponse(
                price_per_seat_cents_monthly = 56,
                price_per_seat_cents_billed = 56,
                monthly_token_limit = 56,
                monthly_document_limit = 56,
                max_seats = 56,
                litellm_budget_cents_per_user = 56,
                has_custom_overrides = True,
        )
        """

    def testEffectiveLimitsResponse(self):
        """Test EffectiveLimitsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
