# coding: utf-8

"""
    Knowledge Stack API

    Knowledge Stack backend API for authentication and knowledge management

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ksapi.models.tenant_response import TenantResponse

class TestTenantResponse(unittest.TestCase):
    """TenantResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TenantResponse:
        """Test TenantResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TenantResponse`
        """
        model = TenantResponse()
        if include_optional:
            return TenantResponse(
                id = '',
                name = '',
                idp_config = { },
                settings = ksapi.models.tenant_settings_response.TenantSettingsResponse(
                    language = 'en', 
                    description = '', 
                    timezone = '', ),
                branding = ksapi.models.tenant_branding_response.TenantBrandingResponse(
                    brand_name = '', 
                    brand_color = '', 
                    logo_url = '', 
                    logo_dark_url = '', 
                    favicon_url = '', 
                    theme_overrides = {
                        'key' : ''
                        }, )
            )
        else:
            return TenantResponse(
                id = '',
                name = '',
                settings = ksapi.models.tenant_settings_response.TenantSettingsResponse(
                    language = 'en', 
                    description = '', 
                    timezone = '', ),
        )
        """

    def testTenantResponse(self):
        """Test TenantResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
