# coding: utf-8

"""
    Knowledge Stack API

    Knowledge Stack backend API for authentication and knowledge management

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ksapi.models.memory_kind import MemoryKind

class TestMemoryKind(unittest.TestCase):
    """MemoryKind unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMemoryKind(self):
        """Test MemoryKind"""
        # inst = MemoryKind()

if __name__ == '__main__':
    unittest.main()
