# coding: utf-8

"""
    Knowledge Stack API

    Knowledge Stack backend API for authentication and knowledge management

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from ksapi.api.path_part_approvals_api import PathPartApprovalsApi


class TestPathPartApprovalsApi(unittest.TestCase):
    """PathPartApprovalsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PathPartApprovalsApi()

    def tearDown(self) -> None:
        pass

    def test_get_path_part_approval(self) -> None:
        """Test case for get_path_part_approval

        Get Path Part Approval Handler
        """
        pass

    def test_set_path_part_approval(self) -> None:
        """Test case for set_path_part_approval

        Set Path Part Approval Handler
        """
        pass


if __name__ == '__main__':
    unittest.main()
