# coding: utf-8

"""
    Knowledge Stack API

    Knowledge Stack backend API for authentication and knowledge management

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, Optional
from uuid import UUID
from ksapi.models.item_permissions import ItemPermissions
from ksapi.models.network_class import NetworkClass
from ksapi.models.path_part_approval_state import PathPartApprovalState
from ksapi.models.user_info import UserInfo
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ApiConnectionResponse(BaseModel):
    """
    Connector response; a discriminated-union variant for folder listings.  ``auth_config`` is intentionally omitted — the secret is write-only and never serialized back.
    """ # noqa: E501
    part_type: Optional[StrictStr] = Field(default='API_CONNECTION', description="Path part type")
    id: UUID
    path_part_id: UUID
    parent_path_part_id: Optional[UUID]
    materialized_path: StrictStr
    tenant_id: UUID
    name: StrictStr
    base_url: StrictStr
    network_class: NetworkClass
    verify_tls: StrictBool
    api_docs: Optional[StrictStr]
    disclaimer_accepted_at: Optional[datetime]
    disclaimer_accepted_by: Optional[UUID]
    approval_state: PathPartApprovalState
    owner: Optional[UserInfo] = None
    permissions: ItemPermissions
    created_at: datetime
    updated_at: datetime
    __properties: ClassVar[List[str]] = ["part_type", "id", "path_part_id", "parent_path_part_id", "materialized_path", "tenant_id", "name", "base_url", "network_class", "verify_tls", "api_docs", "disclaimer_accepted_at", "disclaimer_accepted_by", "approval_state", "owner", "permissions", "created_at", "updated_at"]

    @field_validator('part_type')
    def part_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['API_CONNECTION']):
            raise ValueError("must be one of enum values ('API_CONNECTION')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ApiConnectionResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of owner
        if self.owner:
            _dict['owner'] = self.owner.to_dict()
        # override the default output from pydantic by calling `to_dict()` of permissions
        if self.permissions:
            _dict['permissions'] = self.permissions.to_dict()
        # set to None if parent_path_part_id (nullable) is None
        # and model_fields_set contains the field
        if self.parent_path_part_id is None and "parent_path_part_id" in self.model_fields_set:
            _dict['parent_path_part_id'] = None

        # set to None if api_docs (nullable) is None
        # and model_fields_set contains the field
        if self.api_docs is None and "api_docs" in self.model_fields_set:
            _dict['api_docs'] = None

        # set to None if disclaimer_accepted_at (nullable) is None
        # and model_fields_set contains the field
        if self.disclaimer_accepted_at is None and "disclaimer_accepted_at" in self.model_fields_set:
            _dict['disclaimer_accepted_at'] = None

        # set to None if disclaimer_accepted_by (nullable) is None
        # and model_fields_set contains the field
        if self.disclaimer_accepted_by is None and "disclaimer_accepted_by" in self.model_fields_set:
            _dict['disclaimer_accepted_by'] = None

        # set to None if owner (nullable) is None
        # and model_fields_set contains the field
        if self.owner is None and "owner" in self.model_fields_set:
            _dict['owner'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ApiConnectionResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "part_type": obj.get("part_type") if obj.get("part_type") is not None else 'API_CONNECTION',
            "id": obj.get("id"),
            "path_part_id": obj.get("path_part_id"),
            "parent_path_part_id": obj.get("parent_path_part_id"),
            "materialized_path": obj.get("materialized_path"),
            "tenant_id": obj.get("tenant_id"),
            "name": obj.get("name"),
            "base_url": obj.get("base_url"),
            "network_class": obj.get("network_class"),
            "verify_tls": obj.get("verify_tls"),
            "api_docs": obj.get("api_docs"),
            "disclaimer_accepted_at": obj.get("disclaimer_accepted_at"),
            "disclaimer_accepted_by": obj.get("disclaimer_accepted_by"),
            "approval_state": obj.get("approval_state"),
            "owner": UserInfo.from_dict(obj["owner"]) if obj.get("owner") is not None else None,
            "permissions": ItemPermissions.from_dict(obj["permissions"]) if obj.get("permissions") is not None else None,
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at")
        })
        return _obj


