# coding: utf-8

"""
    Knowledge Stack API

    Knowledge Stack backend API for authentication and knowledge management

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class BrandingLogoType(str, Enum):
    """
    Types of branding logos that can be uploaded.
    """

    """
    allowed enum values
    """
    LOGO = 'logo'
    LOGO_DARK = 'logo_dark'
    FAVICON = 'favicon'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of BrandingLogoType from a JSON string"""
        return cls(json.loads(json_str))


