# coding: utf-8

"""
    Knowledge Stack API

    Knowledge Stack backend API for authentication and knowledge management

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictInt
from typing import Any, ClassVar, Dict, List
from ksapi.models.cell_change import CellChange
from ksapi.models.sheet_visibility_change import SheetVisibilityChange
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CellDiff(BaseModel):
    """
    A cell-level diff of two spreadsheet versions.
    """ # noqa: E501
    changes: List[CellChange]
    added: StrictInt
    removed: StrictInt
    modified: StrictInt
    truncated: StrictBool
    sheet_visibility_changes: List[SheetVisibilityChange]
    __properties: ClassVar[List[str]] = ["changes", "added", "removed", "modified", "truncated", "sheet_visibility_changes"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CellDiff from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in changes (list)
        _items = []
        if self.changes:
            for _item_changes in self.changes:
                if _item_changes:
                    _items.append(_item_changes.to_dict())
            _dict['changes'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in sheet_visibility_changes (list)
        _items = []
        if self.sheet_visibility_changes:
            for _item_sheet_visibility_changes in self.sheet_visibility_changes:
                if _item_sheet_visibility_changes:
                    _items.append(_item_sheet_visibility_changes.to_dict())
            _dict['sheet_visibility_changes'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CellDiff from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "changes": [CellChange.from_dict(_item) for _item in obj["changes"]] if obj.get("changes") is not None else None,
            "added": obj.get("added"),
            "removed": obj.get("removed"),
            "modified": obj.get("modified"),
            "truncated": obj.get("truncated"),
            "sheet_visibility_changes": [SheetVisibilityChange.from_dict(_item) for _item in obj["sheet_visibility_changes"]] if obj.get("sheet_visibility_changes") is not None else None
        })
        return _obj


