# coding: utf-8

"""
    Knowledge Stack API

    Knowledge Stack backend API for authentication and knowledge management

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict
from typing_extensions import Annotated
from uuid import UUID
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CheckpointDetails(BaseModel):
    """
    Agent-internal overlay that replaces older messages in the loaded history.  Written as ``details.checkpoint`` on ``role=SYSTEM`` ThreadMessages. The boundary is explicit via ``upto_message_id`` + ``upto_message_created_at`` so the agent can keep recent messages uncompacted even though the checkpoint message itself is inserted at \"now\".
    """ # noqa: E501
    upto_message_id: UUID = Field(description="Last message covered by this summary (inclusive).")
    upto_message_created_at: datetime = Field(description="created_at of upto_message_id; tiebreaker for identical timestamps.")
    summary: Dict[str, Any] = Field(description="Agent-internal CompressionSummary as a JSON blob. Server does not interpret this; the agent serializes/deserializes via its own model.")
    covered_message_count: Annotated[int, Field(strict=True, ge=0)]
    tokens_before: Annotated[int, Field(strict=True, ge=0)]
    tokens_after: Annotated[int, Field(strict=True, ge=0)]
    summarizer_model: Annotated[str, Field(strict=True, max_length=128)]
    prompt_version: Annotated[str, Field(strict=True, max_length=32)]
    __properties: ClassVar[List[str]] = ["upto_message_id", "upto_message_created_at", "summary", "covered_message_count", "tokens_before", "tokens_after", "summarizer_model", "prompt_version"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CheckpointDetails from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CheckpointDetails from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "upto_message_id": obj.get("upto_message_id"),
            "upto_message_created_at": obj.get("upto_message_created_at"),
            "summary": obj.get("summary"),
            "covered_message_count": obj.get("covered_message_count"),
            "tokens_before": obj.get("tokens_before"),
            "tokens_after": obj.get("tokens_after"),
            "summarizer_model": obj.get("summarizer_model"),
            "prompt_version": obj.get("prompt_version")
        })
        return _obj


