# coding: utf-8

"""
    Knowledge Stack API

    Knowledge Stack backend API for authentication and knowledge management

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, Optional
from typing_extensions import Annotated
from uuid import UUID
from ksapi.models.chunk_metadata_input import ChunkMetadataInput
from ksapi.models.chunk_type import ChunkType
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CreateChunkRequest(BaseModel):
    """
    Request to create a new chunk.
    """ # noqa: E501
    parent_path_id: UUID = Field(description="Parent PathPart ID (must be DOCUMENT_VERSION or SECTION)")
    content: Annotated[str, Field(min_length=1, strict=True)] = Field(description="Chunk text content")
    chunk_type: ChunkType
    chunk_metadata: ChunkMetadataInput
    prev_sibling_path_id: Optional[UUID] = Field(default=None, description="PathPart ID to insert after (null = append to tail)")
    __properties: ClassVar[List[str]] = ["parent_path_id", "content", "chunk_type", "chunk_metadata", "prev_sibling_path_id"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateChunkRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of chunk_metadata
        if self.chunk_metadata:
            _dict['chunk_metadata'] = self.chunk_metadata.to_dict()
        # set to None if prev_sibling_path_id (nullable) is None
        # and model_fields_set contains the field
        if self.prev_sibling_path_id is None and "prev_sibling_path_id" in self.model_fields_set:
            _dict['prev_sibling_path_id'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateChunkRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "parent_path_id": obj.get("parent_path_id"),
            "content": obj.get("content"),
            "chunk_type": obj.get("chunk_type"),
            "chunk_metadata": ChunkMetadataInput.from_dict(obj["chunk_metadata"]) if obj.get("chunk_metadata") is not None else None,
            "prev_sibling_path_id": obj.get("prev_sibling_path_id")
        })
        return _obj


