# coding: utf-8

"""
    Knowledge Stack API

    Knowledge Stack backend API for authentication and knowledge management

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from ksapi.models.information_statistics import InformationStatistics
from ksapi.models.pipeline_state import PipelineState
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class DocumentVersionMetadata(BaseModel):
    """
    Schema for document_version.system_metadata JSONB field.  Tracks S3 URLs for generated artifacts, pipeline execution state, and document statistics. Convention-based paths (images, page screenshots) are derived from document_id/document_version_id via s3_paths helpers, using a flat S3 layout: documents/{document_id}/{document_version_id}/...  Internal conversion artifact paths (standard_pipeline_json_s3, high_accuracy_*_s3) are excluded from API responses via ``Field(exclude=True)`` so we don't expose underlying technology names to external consumers.
    """ # noqa: E501
    source_s3: Optional[StrictStr] = Field(default=None, description="S3 URL to the source document (set by API on upload)")
    cleaned_source_s3: Optional[StrictStr] = Field(default=None, description="S3 URL to watermark-removed source document")
    fast_plaintext_s3: Optional[StrictStr] = Field(default=None, description="S3 URL to the fast plaintext export of the document")
    hash: Optional[StrictStr] = Field(default=None, description="Base64-encoded SHA256 hash of the uploaded source file")
    pipeline_state: Optional[PipelineState] = None
    total_pages: Optional[StrictInt] = Field(default=None, description="Total number of pages in the document")
    total_sections: Optional[StrictInt] = Field(default=None, description="Total number of sections created")
    total_chunks: Optional[StrictInt] = Field(default=None, description="Total number of chunks created")
    total_formulas: Optional[StrictInt] = Field(default=None, description="Total formula cells in the workbook (XLSX only)")
    xlsx_parse_result_s3: Optional[StrictStr] = Field(default=None, description="S3 URI to the full XLSX parse result JSON containing dependency graph, named ranges, and KPI catalog")
    xlsx_named_ranges: Optional[List[Dict[str, Any]]] = Field(default=None, description="Named ranges defined in the workbook (name, ref_string, scope)")
    xlsx_kpi_catalog: Optional[List[Dict[str, Any]]] = Field(default=None, description="KPI (Key Performance Indicator) cells detected by the XLSX parser. Each entry contains a label, computed value, cell address, and driver cell references. Applicable to financial models and operational spreadsheets; not populated for template spreadsheets that lack computed KPI cells.")
    information_statistics: Optional[InformationStatistics] = None
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["source_s3", "cleaned_source_s3", "fast_plaintext_s3", "hash", "pipeline_state", "total_pages", "total_sections", "total_chunks", "total_formulas", "xlsx_parse_result_s3", "xlsx_named_ranges", "xlsx_kpi_catalog", "information_statistics"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DocumentVersionMetadata from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of pipeline_state
        if self.pipeline_state:
            _dict['pipeline_state'] = self.pipeline_state.to_dict()
        # override the default output from pydantic by calling `to_dict()` of information_statistics
        if self.information_statistics:
            _dict['information_statistics'] = self.information_statistics.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if source_s3 (nullable) is None
        # and model_fields_set contains the field
        if self.source_s3 is None and "source_s3" in self.model_fields_set:
            _dict['source_s3'] = None

        # set to None if cleaned_source_s3 (nullable) is None
        # and model_fields_set contains the field
        if self.cleaned_source_s3 is None and "cleaned_source_s3" in self.model_fields_set:
            _dict['cleaned_source_s3'] = None

        # set to None if fast_plaintext_s3 (nullable) is None
        # and model_fields_set contains the field
        if self.fast_plaintext_s3 is None and "fast_plaintext_s3" in self.model_fields_set:
            _dict['fast_plaintext_s3'] = None

        # set to None if hash (nullable) is None
        # and model_fields_set contains the field
        if self.hash is None and "hash" in self.model_fields_set:
            _dict['hash'] = None

        # set to None if total_pages (nullable) is None
        # and model_fields_set contains the field
        if self.total_pages is None and "total_pages" in self.model_fields_set:
            _dict['total_pages'] = None

        # set to None if total_sections (nullable) is None
        # and model_fields_set contains the field
        if self.total_sections is None and "total_sections" in self.model_fields_set:
            _dict['total_sections'] = None

        # set to None if total_chunks (nullable) is None
        # and model_fields_set contains the field
        if self.total_chunks is None and "total_chunks" in self.model_fields_set:
            _dict['total_chunks'] = None

        # set to None if total_formulas (nullable) is None
        # and model_fields_set contains the field
        if self.total_formulas is None and "total_formulas" in self.model_fields_set:
            _dict['total_formulas'] = None

        # set to None if xlsx_parse_result_s3 (nullable) is None
        # and model_fields_set contains the field
        if self.xlsx_parse_result_s3 is None and "xlsx_parse_result_s3" in self.model_fields_set:
            _dict['xlsx_parse_result_s3'] = None

        # set to None if xlsx_named_ranges (nullable) is None
        # and model_fields_set contains the field
        if self.xlsx_named_ranges is None and "xlsx_named_ranges" in self.model_fields_set:
            _dict['xlsx_named_ranges'] = None

        # set to None if xlsx_kpi_catalog (nullable) is None
        # and model_fields_set contains the field
        if self.xlsx_kpi_catalog is None and "xlsx_kpi_catalog" in self.model_fields_set:
            _dict['xlsx_kpi_catalog'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DocumentVersionMetadata from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "source_s3": obj.get("source_s3"),
            "cleaned_source_s3": obj.get("cleaned_source_s3"),
            "fast_plaintext_s3": obj.get("fast_plaintext_s3"),
            "hash": obj.get("hash"),
            "pipeline_state": PipelineState.from_dict(obj["pipeline_state"]) if obj.get("pipeline_state") is not None else None,
            "total_pages": obj.get("total_pages"),
            "total_sections": obj.get("total_sections"),
            "total_chunks": obj.get("total_chunks"),
            "total_formulas": obj.get("total_formulas"),
            "xlsx_parse_result_s3": obj.get("xlsx_parse_result_s3"),
            "xlsx_named_ranges": obj.get("xlsx_named_ranges"),
            "xlsx_kpi_catalog": obj.get("xlsx_kpi_catalog"),
            "information_statistics": InformationStatistics.from_dict(obj["information_statistics"]) if obj.get("information_statistics") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


