# coding: utf-8

"""
    Knowledge Stack API

    Knowledge Stack backend API for authentication and knowledge management

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictInt
from typing import Any, ClassVar, Dict, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class EffectiveLimitsResponse(BaseModel):
    """
    Resolved limits for a tenant (plan defaults + overrides).
    """ # noqa: E501
    price_per_seat_cents_monthly: StrictInt
    price_per_seat_cents_billed: StrictInt
    monthly_token_limit: StrictInt
    monthly_document_limit: StrictInt
    max_seats: Optional[StrictInt]
    litellm_budget_cents_per_user: StrictInt
    has_custom_overrides: StrictBool
    __properties: ClassVar[List[str]] = ["price_per_seat_cents_monthly", "price_per_seat_cents_billed", "monthly_token_limit", "monthly_document_limit", "max_seats", "litellm_budget_cents_per_user", "has_custom_overrides"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EffectiveLimitsResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if max_seats (nullable) is None
        # and model_fields_set contains the field
        if self.max_seats is None and "max_seats" in self.model_fields_set:
            _dict['max_seats'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EffectiveLimitsResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "price_per_seat_cents_monthly": obj.get("price_per_seat_cents_monthly"),
            "price_per_seat_cents_billed": obj.get("price_per_seat_cents_billed"),
            "monthly_token_limit": obj.get("monthly_token_limit"),
            "monthly_document_limit": obj.get("monthly_document_limit"),
            "max_seats": obj.get("max_seats"),
            "litellm_budget_cents_per_user": obj.get("litellm_budget_cents_per_user"),
            "has_custom_overrides": obj.get("has_custom_overrides")
        })
        return _obj


