# coding: utf-8

"""
    Knowledge Stack API

    Knowledge Stack backend API for authentication and knowledge management

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, Optional
from uuid import UUID
from ksapi.models.feedback_rating import FeedbackRating
from ksapi.models.feedback_reason import FeedbackReason
from ksapi.models.feedback_target_type import FeedbackTargetType
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class FeedbackEventResponse(BaseModel):
    """
    Response schema for a single FeedbackEvent.
    """ # noqa: E501
    id: UUID
    target_type: FeedbackTargetType
    target_id: UUID
    user_id: UUID
    rating: FeedbackRating
    reason: FeedbackReason
    comment: Optional[StrictStr]
    extra_metadata: Dict[str, Any]
    created_at: datetime
    updated_at: datetime
    __properties: ClassVar[List[str]] = ["id", "target_type", "target_id", "user_id", "rating", "reason", "comment", "extra_metadata", "created_at", "updated_at"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of FeedbackEventResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if comment (nullable) is None
        # and model_fields_set contains the field
        if self.comment is None and "comment" in self.model_fields_set:
            _dict['comment'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of FeedbackEventResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "target_type": obj.get("target_type"),
            "target_id": obj.get("target_id"),
            "user_id": obj.get("user_id"),
            "rating": obj.get("rating"),
            "reason": obj.get("reason"),
            "comment": obj.get("comment"),
            "extra_metadata": obj.get("extra_metadata"),
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at")
        })
        return _obj


