# coding: utf-8

"""
    Knowledge Stack API

    Knowledge Stack backend API for authentication and knowledge management

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class IngestionMode(str, Enum):
    """
    Ingestion pipeline mode — determines conversion and chunking strategy.
    """

    """
    allowed enum values
    """
    HIGH_ACCURACY = 'high_accuracy'
    STANDARD = 'standard'
    SINGLE_CHUNK = 'single_chunk'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of IngestionMode from a JSON string"""
        return cls(json.loads(json_str))


