# coding: utf-8

"""
    Knowledge Stack API

    Knowledge Stack backend API for authentication and knowledge management

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, Optional
from uuid import UUID
from ksapi.models.input_origin import InputOrigin
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class InputSnapshot(BaseModel):
    """
    One entry of a run's input scope, self-describing its pin semantics.  ``part_type`` is the kind discriminator:  * ``DOCUMENT_VERSION`` — a pinned document version. The DOCUMENT in   the request scope was resolved to its active version at trigger   time; ``path_part_id`` is that DOCUMENT_VERSION path_part and the   entry does not float. * ``FOLDER`` — a live folder reference. ``path_part_id`` is the   FOLDER path_part itself; its contents are NOT captured here and   are enumerated live by the runner (see ``materialized_path`` for   subtree scoping). * ``DATA_SOURCE`` / ``API_CONNECTION`` — a live connector reference   (DB / API). ``path_part_id`` is the connector path_part itself; the   runner queries it live via its connector tools, nothing is captured   here.  The underlying PDO id (DocumentVersion / Folder / connector) is resolved live at run time from ``path_part.metadata_obj_id``, not stored here.
    """ # noqa: E501
    path_part_id: UUID = Field(description="DOCUMENT_VERSION path_part of the pinned input version, or the path_part of a live FOLDER / DATA_SOURCE / API_CONNECTION reference — see ``part_type``.")
    materialized_path: StrictStr
    part_type: StrictStr
    origin: Optional[InputOrigin] = None
    __properties: ClassVar[List[str]] = ["path_part_id", "materialized_path", "part_type", "origin"]

    @field_validator('part_type')
    def part_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['DOCUMENT_VERSION', 'FOLDER', 'DATA_SOURCE', 'API_CONNECTION']):
            raise ValueError("must be one of enum values ('DOCUMENT_VERSION', 'FOLDER', 'DATA_SOURCE', 'API_CONNECTION')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of InputSnapshot from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of InputSnapshot from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "path_part_id": obj.get("path_part_id"),
            "materialized_path": obj.get("materialized_path"),
            "part_type": obj.get("part_type"),
            "origin": obj.get("origin")
        })
        return _obj


