# coding: utf-8

"""
    Knowledge Stack API

    Knowledge Stack backend API for authentication and knowledge management

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class InputOrigin(str, Enum):
    """
    Where a run-snapshot input came from, for auditability.  A run's pinned inputs are merged from three sources at Start; this tags each so an auditor / the FE can tell a definition-mandated common file apart from a file the run's creator chose.
    """

    """
    allowed enum values
    """
    DEFINITION_COMMON = 'DEFINITION_COMMON'
    RUN_REFERENCE = 'RUN_REFERENCE'
    RUN_UPLOAD = 'RUN_UPLOAD'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of InputOrigin from a JSON string"""
        return cls(json.loads(json_str))


