# coding: utf-8

"""
    Knowledge Stack API

    Knowledge Stack backend API for authentication and knowledge management

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class MemoryScope(str, Enum):
    """
    Owner scope for a memory document.  Lowercase values match the request-schema Literals so no mapping layer is needed. ``user`` resolves to /users/{user_id}; ``workflow`` to the workflow definition's path_part. (Tenant scope is deferred.)
    """

    """
    allowed enum values
    """
    USER = 'user'
    WORKFLOW = 'workflow'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of MemoryScope from a JSON string"""
        return cls(json.loads(json_str))


