# coding: utf-8

"""
    Knowledge Stack API

    Knowledge Stack backend API for authentication and knowledge management

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt
from typing import Any, ClassVar, Dict, Optional
from ksapi.models.usage_metric import UsageMetric
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class MeteredQuotaStatus(BaseModel):
    """
    Per-metric usage snapshot for the active period.
    """ # noqa: E501
    metric: UsageMetric
    used: StrictInt = Field(description="Counter for the active period. May be negative if a refund crossed period boundaries.")
    limit: StrictInt = Field(description="Snapshot of the cap at period start")
    period_start: datetime = Field(description="Active period start (UTC)")
    period_end: datetime = Field(description="Active period end (UTC)")
    additional_balance: Optional[StrictInt] = Field(default=0, description="Persistent additional-quota balance for this metric. Unchanged by period rollover; decremented when included is exhausted, incremented on refund or top-up.")
    __properties: ClassVar[List[str]] = ["metric", "used", "limit", "period_start", "period_end", "additional_balance"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MeteredQuotaStatus from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MeteredQuotaStatus from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "metric": obj.get("metric"),
            "used": obj.get("used"),
            "limit": obj.get("limit"),
            "period_start": obj.get("period_start"),
            "period_end": obj.get("period_end"),
            "additional_balance": obj.get("additional_balance") if obj.get("additional_balance") is not None else 0
        })
        return _obj


