# coding: utf-8

"""
    Knowledge Stack API

    Knowledge Stack backend API for authentication and knowledge management

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class PartType(str, Enum):
    """
    Type of path part in the filesystem.
    """

    """
    allowed enum values
    """
    FOLDER = 'FOLDER'
    DOCUMENT = 'DOCUMENT'
    DOCUMENT_VERSION = 'DOCUMENT_VERSION'
    SECTION = 'SECTION'
    CHUNK = 'CHUNK'
    THREAD = 'THREAD'
    THREAD_MESSAGE = 'THREAD_MESSAGE'
    WORKFLOW_DEFINITION = 'WORKFLOW_DEFINITION'
    WORKFLOW_RUN = 'WORKFLOW_RUN'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of PartType from a JSON string"""
        return cls(json.loads(json_str))


