# coding: utf-8

"""
    Knowledge Stack API

    Knowledge Stack backend API for authentication and knowledge management

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class PathPartApprovalState(str, Enum):
    """
    Approval state on any path_part.  The PG enum ``path_part_approval_state`` carries a legacy ``'rejected'`` value that is intentionally NOT mapped here. It survives in the database as a noop — never written, never read. Loading a row whose column holds ``'rejected'`` will fail to decode; prod is empty of such rows.
    """

    """
    allowed enum values
    """
    NOT_REQUIRED = 'not_required'
    PENDING = 'pending'
    APPROVED = 'approved'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of PathPartApprovalState from a JSON string"""
        return cls(json.loads(json_str))


