# coding: utf-8

"""
    Knowledge Stack API

    Knowledge Stack backend API for authentication and knowledge management

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, Optional
from uuid import UUID
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class SectionContentItem(BaseModel):
    """
    Response model for a section item in document version contents.
    """ # noqa: E501
    part_type: StrictStr = Field(description="Path part type")
    path_part_id: UUID = Field(description="PathPart ID")
    name: StrictStr = Field(description="PathPart name")
    parent_path_id: UUID = Field(description="Parent PathPart ID")
    metadata_obj_id: UUID = Field(description="Section ID")
    depth: StrictInt = Field(description="Depth relative to document version root")
    page_number: Optional[StrictInt] = Field(default=None, description="Section page number")
    materialized_path: StrictStr = Field(description="Full materialized path from root")
    system_managed: StrictBool = Field(description="Whether this item is system-managed")
    created_at: datetime = Field(description="Creation timestamp")
    updated_at: datetime = Field(description="Last update timestamp")
    __properties: ClassVar[List[str]] = ["part_type", "path_part_id", "name", "parent_path_id", "metadata_obj_id", "depth", "page_number", "materialized_path", "system_managed", "created_at", "updated_at"]

    @field_validator('part_type')
    def part_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['SECTION']):
            raise ValueError("must be one of enum values ('SECTION')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SectionContentItem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if page_number (nullable) is None
        # and model_fields_set contains the field
        if self.page_number is None and "page_number" in self.model_fields_set:
            _dict['page_number'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SectionContentItem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "part_type": obj.get("part_type"),
            "path_part_id": obj.get("path_part_id"),
            "name": obj.get("name"),
            "parent_path_id": obj.get("parent_path_id"),
            "metadata_obj_id": obj.get("metadata_obj_id"),
            "depth": obj.get("depth"),
            "page_number": obj.get("page_number"),
            "materialized_path": obj.get("materialized_path"),
            "system_managed": obj.get("system_managed"),
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at")
        })
        return _obj


