# coding: utf-8

"""
    Knowledge Stack API

    Knowledge Stack backend API for authentication and knowledge management

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, Optional
from uuid import UUID
from ksapi.models.tenant_user_role import TenantUserRole
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class TenantUserResponse(BaseModel):
    """
    Tenant member response model.
    """ # noqa: E501
    user_id: UUID = Field(description="User ID")
    email: Optional[StrictStr] = Field(default=None, description="User email address")
    first_name: Optional[StrictStr] = Field(default=None, description="User first name")
    last_name: Optional[StrictStr] = Field(default=None, description="User last name")
    role: TenantUserRole
    deactivated_on: Optional[datetime] = Field(default=None, description="Soft-deletion timestamp. NULL = active.")
    is_tenant_idp_managed: StrictBool = Field(description="Whether the user is managed by the tenant's identity provider")
    created_at: datetime = Field(description="Date the user was added to the tenant")
    updated_at: datetime = Field(description="Date the user was updated")
    __properties: ClassVar[List[str]] = ["user_id", "email", "first_name", "last_name", "role", "deactivated_on", "is_tenant_idp_managed", "created_at", "updated_at"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TenantUserResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if email (nullable) is None
        # and model_fields_set contains the field
        if self.email is None and "email" in self.model_fields_set:
            _dict['email'] = None

        # set to None if first_name (nullable) is None
        # and model_fields_set contains the field
        if self.first_name is None and "first_name" in self.model_fields_set:
            _dict['first_name'] = None

        # set to None if last_name (nullable) is None
        # and model_fields_set contains the field
        if self.last_name is None and "last_name" in self.model_fields_set:
            _dict['last_name'] = None

        # set to None if deactivated_on (nullable) is None
        # and model_fields_set contains the field
        if self.deactivated_on is None and "deactivated_on" in self.model_fields_set:
            _dict['deactivated_on'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TenantUserResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "user_id": obj.get("user_id"),
            "email": obj.get("email"),
            "first_name": obj.get("first_name"),
            "last_name": obj.get("last_name"),
            "role": obj.get("role"),
            "deactivated_on": obj.get("deactivated_on"),
            "is_tenant_idp_managed": obj.get("is_tenant_idp_managed"),
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at")
        })
        return _obj


