# coding: utf-8

"""
    Knowledge Stack API

    Knowledge Stack backend API for authentication and knowledge management

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, Optional
from typing_extensions import Annotated
from ksapi.models.input import Input
from ksapi.models.tool_status import ToolStatus
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ToolPart(BaseModel):
    """
    ToolPart
    """ # noqa: E501
    id: StrictStr = Field(description="Stable per-message part id (uuid)")
    seq: Annotated[int, Field(strict=True, ge=0)] = Field(description="0-based order within the message")
    start_time: datetime
    end_time: Optional[datetime] = None
    kind: Optional[StrictStr] = 'tool'
    tool_call_id: StrictStr
    tool_name: StrictStr
    input: Optional[Input] = None
    status: Optional[ToolStatus] = None
    result: Optional[Any] = None
    is_error: Optional[StrictBool] = False
    duration_ms: Optional[StrictInt] = None
    extras: Optional[Dict[str, Any]] = None
    __properties: ClassVar[List[str]] = ["id", "seq", "start_time", "end_time", "kind", "tool_call_id", "tool_name", "input", "status", "result", "is_error", "duration_ms", "extras"]

    @field_validator('kind')
    def kind_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['tool']):
            raise ValueError("must be one of enum values ('tool')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ToolPart from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of input
        if self.input:
            _dict['input'] = self.input.to_dict()
        # set to None if end_time (nullable) is None
        # and model_fields_set contains the field
        if self.end_time is None and "end_time" in self.model_fields_set:
            _dict['end_time'] = None

        # set to None if input (nullable) is None
        # and model_fields_set contains the field
        if self.input is None and "input" in self.model_fields_set:
            _dict['input'] = None

        # set to None if result (nullable) is None
        # and model_fields_set contains the field
        if self.result is None and "result" in self.model_fields_set:
            _dict['result'] = None

        # set to None if duration_ms (nullable) is None
        # and model_fields_set contains the field
        if self.duration_ms is None and "duration_ms" in self.model_fields_set:
            _dict['duration_ms'] = None

        # set to None if extras (nullable) is None
        # and model_fields_set contains the field
        if self.extras is None and "extras" in self.model_fields_set:
            _dict['extras'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ToolPart from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "seq": obj.get("seq"),
            "start_time": obj.get("start_time"),
            "end_time": obj.get("end_time"),
            "kind": obj.get("kind") if obj.get("kind") is not None else 'tool',
            "tool_call_id": obj.get("tool_call_id"),
            "tool_name": obj.get("tool_name"),
            "input": Input.from_dict(obj["input"]) if obj.get("input") is not None else None,
            "status": obj.get("status"),
            "result": obj.get("result"),
            "is_error": obj.get("is_error") if obj.get("is_error") is not None else False,
            "duration_ms": obj.get("duration_ms"),
            "extras": obj.get("extras")
        })
        return _obj


