# coding: utf-8

"""
    Knowledge Stack API

    Knowledge Stack backend API for authentication and knowledge management

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List
from uuid import UUID
from ksapi.models.abcd_path_snapshot import ABCDPathSnapshot
from ksapi.models.workflow_runner_type import WorkflowRunnerType
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class WorkflowRunSnapshot(BaseModel):
    """
    Frozen ABCD configuration captured at workflow trigger time.
    """ # noqa: E501
    workflow_definition_id: UUID
    workflow_name: StrictStr
    runner_type: WorkflowRunnerType
    user_id: UUID
    max_run_duration_seconds: StrictInt
    sources: List[ABCDPathSnapshot]
    instructions: List[ABCDPathSnapshot]
    outputs: List[ABCDPathSnapshot]
    template: ABCDPathSnapshot
    __properties: ClassVar[List[str]] = ["workflow_definition_id", "workflow_name", "runner_type", "user_id", "max_run_duration_seconds", "sources", "instructions", "outputs", "template"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of WorkflowRunSnapshot from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in sources (list)
        _items = []
        if self.sources:
            for _item_sources in self.sources:
                if _item_sources:
                    _items.append(_item_sources.to_dict())
            _dict['sources'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in instructions (list)
        _items = []
        if self.instructions:
            for _item_instructions in self.instructions:
                if _item_instructions:
                    _items.append(_item_instructions.to_dict())
            _dict['instructions'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in outputs (list)
        _items = []
        if self.outputs:
            for _item_outputs in self.outputs:
                if _item_outputs:
                    _items.append(_item_outputs.to_dict())
            _dict['outputs'] = _items
        # override the default output from pydantic by calling `to_dict()` of template
        if self.template:
            _dict['template'] = self.template.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of WorkflowRunSnapshot from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "workflow_definition_id": obj.get("workflow_definition_id"),
            "workflow_name": obj.get("workflow_name"),
            "runner_type": obj.get("runner_type"),
            "user_id": obj.get("user_id"),
            "max_run_duration_seconds": obj.get("max_run_duration_seconds"),
            "sources": [ABCDPathSnapshot.from_dict(_item) for _item in obj["sources"]] if obj.get("sources") is not None else None,
            "instructions": [ABCDPathSnapshot.from_dict(_item) for _item in obj["instructions"]] if obj.get("instructions") is not None else None,
            "outputs": [ABCDPathSnapshot.from_dict(_item) for _item in obj["outputs"]] if obj.get("outputs") is not None else None,
            "template": ABCDPathSnapshot.from_dict(obj["template"]) if obj.get("template") is not None else None
        })
        return _obj


