# coding: utf-8

"""
    Knowledge Stack API

    Knowledge Stack backend API for authentication and knowledge management

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from uuid import UUID
from ksapi.models.cited_chunk import CitedChunk
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class XlsxCellAnchorOutput(BaseModel):
    """
    One citation anchored to a cell in an .xlsx deliverable.
    """ # noqa: E501
    type: Optional[StrictStr] = 'xlsx_cell'
    sheet_name: StrictStr
    cell_address: StrictStr = Field(description="Coordinate like 'B23'.")
    citations: List[CitedChunk] = Field(description="Cited chunks in the order they appeared in the comment body, each with the source-document snapshot resolved at save time.")
    anchor_text: Optional[Annotated[str, Field(strict=True, max_length=160)]] = Field(default='', description="Cached cell value at this anchor, for FE display. NOT the cited quote. Empty when the cell holds a formula whose cache has not been refreshed.")
    chunk_ids: List[UUID] = Field(description="Flat projection of cited chunk_ids — kept for FE back-compat.  Prefer ``citations`` for new code: each entry already carries the source-document context the Citations panel needs, no follow-up ``/v1/chunks/bulk`` call required. Derived-only — ``citations`` is the single source of truth.")
    __properties: ClassVar[List[str]] = ["type", "sheet_name", "cell_address", "citations", "anchor_text", "chunk_ids"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['xlsx_cell']):
            raise ValueError("must be one of enum values ('xlsx_cell')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of XlsxCellAnchorOutput from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "chunk_ids",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in citations (list)
        _items = []
        if self.citations:
            for _item_citations in self.citations:
                if _item_citations:
                    _items.append(_item_citations.to_dict())
            _dict['citations'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of XlsxCellAnchorOutput from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "type": obj.get("type") if obj.get("type") is not None else 'xlsx_cell',
            "sheet_name": obj.get("sheet_name"),
            "cell_address": obj.get("cell_address"),
            "citations": [CitedChunk.from_dict(_item) for _item in obj["citations"]] if obj.get("citations") is not None else None,
            "anchor_text": obj.get("anchor_text") if obj.get("anchor_text") is not None else '',
            "chunk_ids": obj.get("chunk_ids")
        })
        return _obj


